[package]
name = "eva"
version = "0.2.7"
authors = ["NerdyPepper <akshayoppiliappan@gmail.com>"]
edition = "2018"
description = "Calculator REPL similar to bc(1)"
homepage = "https://github.com/nerdypepper/eva"
repository = "https://github.com/nerdypepper/eva"
readme = "./readme.md"
keywords = ["calculator", "repl", "math", "cli", "bc"]
categories = ["command-line-interface", "science", "parser-implementations"]
license = "MIT"

[dependencies]
rustyline   = "4.1.0"
clap        = "2.32.0"
radix_fmt   = "1.0.0"
lazy_static = "1.3.0"
directories = "2.0.1"
regex       = "1.1.7"
num         = "0.2"
