[package]
name = "eva"
version = "0.2.4"
authors = ["NerdyPepper <akshayoppiliappan@gmail.com>"]
edition = "2018"
description = "Calculator REPL similar to bc(1)"
homepage = "https://github.com/nerdypepper/eva"
repository = "https://github.com/nerdypepper/eva"
readme = "./readme.md"
keywords = ["calculator", "repl", "math", "cli", "bc"]
categories = ["command-line-interface", "science", "parser-implementations"]
license = "MIT"

[dependencies]
rustyline   = "3.0.0"
clap        = "2.32.0"
radix_fmt   = "0.1.1"
lazy_static = "1.3.0"
